# Sofle config

# Habilitar display OLED
CONFIG_ZMK_DISPLAY=y

# Habilitar encoders rotativos
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Descomentar para habilitar RGB underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
